import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BottomNav from "./components/bottom-nav";
import SideNav from "./components/side-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="flex h-screen flex-col lg:flex-row">
          <div className="hidden lg:block w-full flex-none lg:w-64">
            <SideNav />
          </div>

          <div className="flex-grow p-6 overflow-y-auto">{children}</div>

          <div>
            <BottomNav />
          </div>
        </div>
      </body>
    </html>
  );
}
